namespace DoorCEGenerator.Application.IntermediateModel.StructuralUnitRepresentations;

public abstract class UCCallableOperation(CodeGenerationProfile codeGenerationProfile) : Operation(codeGenerationProfile);