//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Praca/VSCodeProjects/rsl-bis/AntlrCSharp/DScript.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IDScriptVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] DScriptParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.usecase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsecase([NotNull] DScriptParser.UsecaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.ucconditions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUcconditions([NotNull] DScriptParser.UcconditionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.conditions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditions([NotNull] DScriptParser.ConditionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] DScriptParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.contextcondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContextcondition([NotNull] DScriptParser.ContextconditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.valuecondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValuecondition([NotNull] DScriptParser.ValueconditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.mainscenario"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMainscenario([NotNull] DScriptParser.MainscenarioContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.scenarios"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScenarios([NotNull] DScriptParser.ScenariosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.scenario"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScenario([NotNull] DScriptParser.ScenarioContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.sentences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentences([NotNull] DScriptParser.SentencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.altsentences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltsentences([NotNull] DScriptParser.AltsentencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.sentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentence([NotNull] DScriptParser.SentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.altsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltsentence([NotNull] DScriptParser.AltsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.condsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondsentence([NotNull] DScriptParser.CondsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.endsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndsentence([NotNull] DScriptParser.EndsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.resultsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResultsentence([NotNull] DScriptParser.ResultsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.rejoinsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRejoinsentence([NotNull] DScriptParser.RejoinsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResult([NotNull] DScriptParser.ResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.repsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepsentence([NotNull] DScriptParser.RepsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.svosentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSvosentence([NotNull] DScriptParser.SvosentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.altsvosentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltsvosentence([NotNull] DScriptParser.AltsvosentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStep([NotNull] DScriptParser.StepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.systemstep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSystemstep([NotNull] DScriptParser.SystemstepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.toactorpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToactorpredicate([NotNull] DScriptParser.ToactorpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.showpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShowpredicate([NotNull] DScriptParser.ShowpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.closepredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosepredicate([NotNull] DScriptParser.ClosepredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.tosystempredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTosystempredicate([NotNull] DScriptParser.TosystempredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.readpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadpredicate([NotNull] DScriptParser.ReadpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.updatepredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdatepredicate([NotNull] DScriptParser.UpdatepredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.deletepredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeletepredicate([NotNull] DScriptParser.DeletepredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.checkpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCheckpredicate([NotNull] DScriptParser.CheckpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.executepredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecutepredicate([NotNull] DScriptParser.ExecutepredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.userstep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUserstep([NotNull] DScriptParser.UserstepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.selectpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectpredicate([NotNull] DScriptParser.SelectpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.enterpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnterpredicate([NotNull] DScriptParser.EnterpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.invoke"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvoke([NotNull] DScriptParser.InvokeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.sysinvoke"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSysinvoke([NotNull] DScriptParser.SysinvokeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.notiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotiondef([NotNull] DScriptParser.NotiondefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.viewnotion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitViewnotion([NotNull] DScriptParser.ViewnotionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.viewtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitViewtype([NotNull] DScriptParser.ViewtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.triggernotion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriggernotion([NotNull] DScriptParser.TriggernotionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.triggertype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriggertype([NotNull] DScriptParser.TriggertypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.namesandlabels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamesandlabels([NotNull] DScriptParser.NamesandlabelsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.datanotion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatanotion([NotNull] DScriptParser.DatanotionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] DScriptParser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] DScriptParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.unique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnique([NotNull] DScriptParser.UniqueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.required"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequired([NotNull] DScriptParser.RequiredContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.auxiliary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAuxiliary([NotNull] DScriptParser.AuxiliaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.multnotion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultnotion([NotNull] DScriptParser.MultnotionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.datatype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatatype([NotNull] DScriptParser.DatatypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNames([NotNull] DScriptParser.NamesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.actor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActor([NotNull] DScriptParser.ActorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.notion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotion([NotNull] DScriptParser.NotionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] DScriptParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] DScriptParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.uilabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUilabel([NotNull] DScriptParser.UilabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] DScriptParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.altlabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltlabel([NotNull] DScriptParser.AltlabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DScriptParser.labelref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabelref([NotNull] DScriptParser.LabelrefContext context);
}
