// <auto-generated />
using System;
using System.Collections.Generic;
using DoorCEModel.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoorCEServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124153813_CodeContents")]
    partial class CodeContents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcquisitionAppDataResource", b =>
                {
                    b.Property<int>("AcquisitionAppId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceResourcesId")
                        .HasColumnType("integer");

                    b.HasKey("AcquisitionAppId", "SourceResourcesId");

                    b.HasIndex("SourceResourcesId");

                    b.ToTable("AcquisitionAppDataResource");
                });

            modelBuilder.Entity("ContactDataOwnableResource", b =>
                {
                    b.Property<int>("ContactsId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourcesId")
                        .HasColumnType("integer");

                    b.HasKey("ContactsId", "ResourcesId");

                    b.HasIndex("ResourcesId");

                    b.ToTable("ContactDataOwnableResource");
                });

            modelBuilder.Entity("DataSchemaNamespace", b =>
                {
                    b.Property<int>("DataSchemaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsedNamespacesId")
                        .HasColumnType("integer");

                    b.HasKey("DataSchemaId", "UsedNamespacesId");

                    b.HasIndex("UsedNamespacesId");

                    b.ToTable("DataSchemaNamespace");
                });

            modelBuilder.Entity("DataServiceStandard", b =>
                {
                    b.Property<int>("ConformsToId")
                        .HasColumnType("integer");

                    b.Property<int>("DataServicesId")
                        .HasColumnType("integer");

                    b.HasKey("ConformsToId", "DataServicesId");

                    b.HasIndex("DataServicesId");

                    b.ToTable("DataServiceStandard");
                });

            modelBuilder.Entity("DatasetDatasetSeries", b =>
                {
                    b.Property<int>("DatasetsId")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.HasKey("DatasetsId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("DatasetDatasetSeries");
                });

            modelBuilder.Entity("DatasetStandard", b =>
                {
                    b.Property<int>("ConformsToId")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetsId")
                        .HasColumnType("integer");

                    b.HasKey("ConformsToId", "DatasetsId");

                    b.HasIndex("DatasetsId");

                    b.ToTable("DatasetStandard");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("Agents");

                    b.HasDiscriminator().HasValue("Agent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.ContactData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("ContactDatas");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Editorship", b =>
                {
                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceLinkId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("AgentId", "ResourceLinkId");

                    b.HasIndex("ResourceLinkId");

                    b.ToTable("Editors", (string)null);
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Membership", b =>
                {
                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("OrganisationId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.OwnableResource", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, string>>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("IconUri")
                        .HasColumnType("text");

                    b.Property<int?>("ResponsibleOrganisationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsiblePersonId")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, string>>("Title")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleOrganisationId");

                    b.HasIndex("ResponsiblePersonId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("OwnableResources");

                    b.HasDiscriminator().HasValue("OwnableResource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.ResourceEditorshipsLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ResourceEditorshipsLinks");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Applications.AcquisitionApp", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiveResourceId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("AcquisitionApps");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Applications.AppDataSpecification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppDataSpecification");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Applications.AppTemplate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VersionOfId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchemaId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.HasIndex("VersionOfId");

                    b.ToTable("AppTemplates");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Applications.UseCaseScenarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("ScenariosContents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UseCaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppTemplateId");

                    b.ToTable("UseCaseScenarios");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.BinaryContents.DataFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataFiles");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.BinaryContents.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.CodeContents.CodeFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeContents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("CodeFiles");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.CodeContents.CodePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeFramework")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("CodePackages");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.Namespace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Iri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Namespaces");

                    b.HasDiscriminator().HasValue("Namespace");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.NamespaceElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NamespaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NamespaceId");

                    b.ToTable("NamespaceElements");

                    b.HasDiscriminator().HasValue("NamespaceElement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.SchemaSeries", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<short[]>("Type")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("SchemaSeries");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DatasetContents.DataItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConceptUri")
                        .HasColumnType("text");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, object>>("Values")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DataItems");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AccessStatus")
                        .HasColumnType("smallint");

                    b.PrimitiveCollection<string[]>("AccessUrl")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long?>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<Dictionary<string, string>>("Checksum")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<string>("CompressionFormat")
                        .HasColumnType("text");

                    b.Property<int?>("DataServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, string>>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("text");

                    b.Property<int?>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MediaType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SchemaId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, string>>("Title")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataServiceId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("SchemaId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.Standard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("Standards");

                    b.HasDiscriminator().HasValue("Standard");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Organisation", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.Agents.Agent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Organisation");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Person", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.Agents.Agent");

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("GivenNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Person");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.Catalogue", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.Agents.OwnableResource");

                    b.Property<int?>("PartOfId")
                        .HasColumnType("integer");

                    b.HasIndex("PartOfId");

                    b.HasDiscriminator().HasValue("Catalogue");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.CataloguedResource", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.Agents.OwnableResource");

                    b.Property<short>("AccessRights")
                        .HasColumnType("smallint");

                    b.PrimitiveCollection<string[]>("ApplicableLegislations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("CatalogueId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Licences")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Themes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasIndex("CatalogueId");

                    b.HasDiscriminator().HasValue("CataloguedResource");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.CustomNamespace", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.DataSchemas.Namespace");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("CustomNamespace");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.Concept", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.DataSchemas.NamespaceElement");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("SchemaId")
                        .HasColumnType("integer");

                    b.HasIndex("SchemaId");

                    b.HasDiscriminator().HasValue("Concept");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.Property", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.DataSchemas.NamespaceElement");

                    b.Property<int?>("ConceptId")
                        .HasColumnType("integer");

                    b.Property<bool>("Multiple")
                        .HasColumnType("boolean");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<bool>("Unique")
                        .HasColumnType("boolean");

                    b.HasIndex("ConceptId");

                    b.HasDiscriminator().HasValue("Property");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.DataSchema", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.Datasets.Standard");

                    b.Property<int>("InSeriesId")
                        .HasColumnType("integer");

                    b.HasIndex("InSeriesId");

                    b.HasDiscriminator().HasValue("DataSchema");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.DataResource", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.Datasets.CataloguedResource");

                    b.Property<string>("Frequency")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("GeographicalCoverage")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TemporalCoverage")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasDiscriminator().HasValue("DataResource");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.DataService", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.Datasets.CataloguedResource");

                    b.PrimitiveCollection<string[]>("Documentation")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("EndpointDescription")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Format")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasDiscriminator().HasValue("DataService");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.Attribute", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.DataSchemas.Property");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Attribute");
                });

            modelBuilder.Entity("DoorCEServer.Infrastructure.DataModel.DataSchemas.Reference", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.DataSchemas.Property");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasIndex("TypeId");

                    b.HasDiscriminator().HasValue("Reference");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.Dataset", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.Datasets.DataResource");

                    b.PrimitiveCollection<string[]>("Documentation")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Provenance")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("SchemaId")
                        .HasColumnType("integer");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<short[]>("Type")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionNotes")
                        .HasColumnType("text");

                    b.Property<int?>("VersionOfId")
                        .HasColumnType("integer");

                    b.HasIndex("SchemaId");

                    b.HasIndex("TargetId");

                    b.HasIndex("VersionOfId");

                    b.ToTable("OwnableResources", t =>
                        {
                            t.Property("Documentation")
                                .HasColumnName("Dataset_Documentation");

                            t.Property("Status")
                                .HasColumnName("Dataset_Status");
                        });

                    b.HasDiscriminator().HasValue("Dataset");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.DatasetSeries", b =>
                {
                    b.HasBaseType("DoorCEModel.Infrastructure.DataModel.Datasets.DataResource");

                    b.HasDiscriminator().HasValue("DatasetSeries");
                });

            modelBuilder.Entity("AcquisitionAppDataResource", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Applications.AcquisitionApp", null)
                        .WithMany()
                        .HasForeignKey("AcquisitionAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.DataResource", null)
                        .WithMany()
                        .HasForeignKey("SourceResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContactDataOwnableResource", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.ContactData", null)
                        .WithMany()
                        .HasForeignKey("ContactsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.OwnableResource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataSchemaNamespace", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.DataSchema", null)
                        .WithMany()
                        .HasForeignKey("DataSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.Namespace", null)
                        .WithMany()
                        .HasForeignKey("UsedNamespacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataServiceStandard", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Standard", null)
                        .WithMany()
                        .HasForeignKey("ConformsToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.DataService", null)
                        .WithMany()
                        .HasForeignKey("DataServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatasetDatasetSeries", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Dataset", null)
                        .WithMany()
                        .HasForeignKey("DatasetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.DatasetSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatasetStandard", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Standard", null)
                        .WithMany()
                        .HasForeignKey("ConformsToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Dataset", null)
                        .WithMany()
                        .HasForeignKey("DatasetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.ContactData", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.Agent", "Agent")
                        .WithMany("Contacts")
                        .HasForeignKey("AgentId");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Editorship", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.Agent", "Agent")
                        .WithMany("EditorRoles")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.ResourceEditorshipsLink", "ResourceLink")
                        .WithMany("EditorRoles")
                        .HasForeignKey("ResourceLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("ResourceLink");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Membership", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.Organisation", "Organisation")
                        .WithMany("MemberRoles")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.Person", "Person")
                        .WithMany("MemberRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.OwnableResource", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.ResourceEditorshipsLink", "EditorshipsLink")
                        .WithOne()
                        .HasForeignKey("DoorCEModel.Infrastructure.DataModel.Agents.OwnableResource", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.Organisation", "ResponsibleOrganisation")
                        .WithMany("ManagedResources")
                        .HasForeignKey("ResponsibleOrganisationId");

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.Person", "ResponsiblePerson")
                        .WithMany("ManagedResources")
                        .HasForeignKey("ResponsiblePersonId");

                    b.Navigation("EditorshipsLink");

                    b.Navigation("ResponsibleOrganisation");

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Applications.AcquisitionApp", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.DataResource", "ActiveResource")
                        .WithMany()
                        .HasForeignKey("ActiveResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.ResourceEditorshipsLink", "EditorshipsLink")
                        .WithOne()
                        .HasForeignKey("DoorCEModel.Infrastructure.DataModel.Applications.AcquisitionApp", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Applications.AppTemplate", "Template")
                        .WithMany("Apps")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActiveResource");

                    b.Navigation("EditorshipsLink");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Applications.AppDataSpecification", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Applications.AppTemplate", null)
                        .WithOne("DataSpecification")
                        .HasForeignKey("DoorCEModel.Infrastructure.DataModel.Applications.AppDataSpecification", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Applications.AppTemplate", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.ResourceEditorshipsLink", "EditorshipsLink")
                        .WithOne()
                        .HasForeignKey("DoorCEModel.Infrastructure.DataModel.Applications.AppTemplate", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.DataSchema", "Schema")
                        .WithMany()
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Applications.AppTemplate", "VersionOf")
                        .WithMany("Versions")
                        .HasForeignKey("VersionOfId");

                    b.Navigation("EditorshipsLink");

                    b.Navigation("Schema");

                    b.Navigation("VersionOf");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Applications.UseCaseScenarios", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Applications.AppTemplate", null)
                        .WithMany("UseCases")
                        .HasForeignKey("AppTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.CodeContents.CodeFile", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.CodeContents.CodePackage", "Package")
                        .WithMany("Files")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.CodeContents.CodePackage", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Applications.AppTemplate", "Template")
                        .WithMany("Packages")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.NamespaceElement", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.Namespace", "Namespace")
                        .WithMany()
                        .HasForeignKey("NamespaceId");

                    b.Navigation("Namespace");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.SchemaSeries", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.DataSchema", "Current")
                        .WithMany()
                        .HasForeignKey("CurrentId");

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.ResourceEditorshipsLink", "EditorshipsLink")
                        .WithOne()
                        .HasForeignKey("DoorCEModel.Infrastructure.DataModel.DataSchemas.SchemaSeries", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Current");

                    b.Navigation("EditorshipsLink");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DatasetContents.DataItem", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Dataset", "Dataset")
                        .WithMany("Items")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.Distribution", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.DataService", "DataService")
                        .WithMany("Distributions")
                        .HasForeignKey("DataServiceId");

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Dataset", "Dataset")
                        .WithMany("Distributions")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.DataSchema", "Schema")
                        .WithMany()
                        .HasForeignKey("SchemaId");

                    b.Navigation("DataService");

                    b.Navigation("Dataset");

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Person", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Agents.UserAccount", "Account")
                        .WithOne("Person")
                        .HasForeignKey("DoorCEModel.Infrastructure.DataModel.Agents.Person", "AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.Catalogue", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Catalogue", "PartOf")
                        .WithMany("Parts")
                        .HasForeignKey("PartOfId");

                    b.Navigation("PartOf");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.CataloguedResource", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Catalogue", "Catalogue")
                        .WithMany("Resources")
                        .HasForeignKey("CatalogueId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Catalogue");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.Concept", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.DataSchema", "Schema")
                        .WithMany("Concepts")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.Property", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.Concept", "Concept")
                        .WithMany("Properties")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.DataSchema", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.SchemaSeries", "InSeries")
                        .WithMany("Schemas")
                        .HasForeignKey("InSeriesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("InSeries");
                });

            modelBuilder.Entity("DoorCEServer.Infrastructure.DataModel.DataSchemas.Reference", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.Concept", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.Dataset", b =>
                {
                    b.HasOne("DoorCEModel.Infrastructure.DataModel.DataSchemas.DataSchema", "Schema")
                        .WithMany()
                        .HasForeignKey("SchemaId");

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Dataset", "Target")
                        .WithMany("Source")
                        .HasForeignKey("TargetId");

                    b.HasOne("DoorCEModel.Infrastructure.DataModel.Datasets.Dataset", "VersionOf")
                        .WithMany()
                        .HasForeignKey("VersionOfId");

                    b.Navigation("Schema");

                    b.Navigation("Target");

                    b.Navigation("VersionOf");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Agent", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("EditorRoles");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.ResourceEditorshipsLink", b =>
                {
                    b.Navigation("EditorRoles");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.UserAccount", b =>
                {
                    b.Navigation("Person");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Applications.AppTemplate", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("DataSpecification")
                        .IsRequired();

                    b.Navigation("Packages");

                    b.Navigation("UseCases");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.CodeContents.CodePackage", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.SchemaSeries", b =>
                {
                    b.Navigation("Schemas");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Organisation", b =>
                {
                    b.Navigation("ManagedResources");

                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Agents.Person", b =>
                {
                    b.Navigation("ManagedResources");

                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.Catalogue", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.Concept", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.DataSchemas.DataSchema", b =>
                {
                    b.Navigation("Concepts");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.DataService", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("DoorCEModel.Infrastructure.DataModel.Datasets.Dataset", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("Items");

                    b.Navigation("Source");
                });
#pragma warning restore 612, 618
        }
    }
}
